# Generated by Django 5.2.6 on 2025-09-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='original_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='tweets.tweet'),
        ),
    ]
